### ISSUE TITLE
add in more content for "Our Productions" 

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/cinema2015#15]

**Comment by dstrogiy** [comment]
I added a bunch!
Now that I'm thinking about, maybe we should add an accordion for the crew list? Cause those are super-long for several films

**Comment by dstrogiy** [comment]
![tumblr_naiac2su9y1txufzyo1_400](https://cloud.githubusercontent.com/assets/6132788/12648400/cd7bffda-c5a7-11e5-99e0-e6e0a3c6db7e.gif)
