### ISSUE TITLE
Ability to add a gallery of images to a post

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/cinema2015#18]
I think they will want this functionality on news posts & production posts

**Comment by PeytonSorah** [comment]
On some of these posts the featured image is wider than it is tall and there is not much content. When this happens the gallery is only visible after a huge empty white space. If we have time we should come up with a solution to this.

**Comment by dstrogiy** [comment]
![giphy-2](https://cloud.githubusercontent.com/assets/6132788/12823435/fb57788e-cb39-11e5-9f74-f3f5ed748af9.gif)
