### ISSUE TITLE
Last Minute Edits

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/cinema2015#24]
Home page
- [x]  We'd like more pictures and videos on the homepage (videos can be found here: https://vimeo.com/vcucinema Behind the Scenes at VCUarts Cinema is a good one).

Curriculum Timeline
- [x]  Instead of "BA in Cinema," let's call it "Overview of Cinema BA"
- [x]  Let's change the photo on the curriculum timeline page, maybe to a photo of students.

Course Descriptions
- [x]  Remove CINE 401

Faculty
- [x]  Reposition the headshots of faculty on the first faculty page, specifically Anne Chapman and J.M. Tyree.
- [x]  For Jim Contner's faculty bio, "Vampire Slayer" should be "Campire Slayer"
- [x]  For Anne Chapman's faculty bio, "Childsplay" should be "Child's Play," and in the first paragraph she's worked in casting on every, not ever film

Student-Industry Relations
- [x]  Rewrite the third paragraph as:
Eight current students and alumni also worked on “Imperium” starring Daniel Radcliffe.
“TURN: Washington’s Spies” has shot three season in Richmond.  Roughly twenty students and alumni have worked on the production each season. Additionally, several faculty members work on the production, and arrange for visits to the set and for tours with Turn's art department.

Cinematheque
- [x]  We should add in a listing of the Spring 2016 Cinematheque films--all of the films are listed at http://arts.vcu.edu/cinema/cinematheque/ 

News + Events
- [x]  Let's add the first post from http://arts.vcu.edu/cinema/2016/02/20/1930/

**Comment by dstrogiy** [comment]
- [ ] pull a sample image for homepage latest post if no featured img is set

**Comment by PeytonSorah** [comment]
Good looks @dstrogiy!
