### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/cinema2015#3]
- [x] The First Year of Cinema -- they are typically not doing their second major, they're doing their Gen Eds. Can we list the Gen Eds on the right?

- [x] Can you add somewhere that this is based off a 15cr semester? 

- [x] What are you guys thinking for the video content portion? We were thinking it would be sweet if it was like a Prezi-- when you click on the courses it would zoom in and then the video/course description would appear? We can 

- [x]  For the Second Major Double minor, we think that we should list the amount of credits that they have to take to keep it in the three year time frame. -- We also want to maybe provide some examples... Maybe on the right side it could sort of branch out into three columns (Second Major, Double Minor, Dual Degree) and we could provide actual course work?

**Comment by PeytonSorah** [comment]
@dstrogiy I figure we can implement your trailer overlay for these vids too

**Comment by dstrogiy** [comment]
@PeytonSorah good thinking pal

**Comment by dstrogiy** [comment]
Should we wait until we get feedback on beta before implementing the popup, etc?

**Comment by PeytonSorah** [comment]
probs

**Comment by dstrogiy** [comment]
Good job everyone
