### ISSUE TITLE
subnav disappears on single pages

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/cinema2015#7]

**Comment by dstrogiy** [comment]
only on Faculty, right?

**Comment by PeytonSorah** [comment]
I believe so, but if we end up adding more post types it might show up again.

**Comment by dstrogiy** [comment]
It basically takes several custom CSS lines to make it show up, so I think we can deal with it on case to case basis in the future. Unfortunately I can't think of an automatic way to make it work
