### ISSUE TITLE
What's the deal with Student Stories?

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/cinema2015#8]
Need to get this content-not sure if it should be cpt or just a page.

**Comment by dstrogiy** [comment]
Yeah uh I just started building a blog template for that - but maybe it's not needed?

**Comment by PeytonSorah** [comment]
It won't hurt to have it started-we can always switch it back to a page down the road if needed.

**Comment by dstrogiy** [comment]
I lied - I started building another template, not this one lol

**Comment by dstrogiy** [comment]
Let's leave it as it is for beta and see what the say. Maybe it could work as a static page.
